###
GET http://localhost:5000/employees

###
POST http://localhost:5000/employees
Content-Type: application/json

{
    "firstName": "hennry",
    "lastName": "Cox",
    "department": "Quadparser",
    "email": "Hcox@example.edu",
    "birthday": "1998-10-15"
}

###
PUT http://localhost:5000/employees/679be01d535693251cfe96d0
Content-Type: application/json

{
    "firstName": "Frank",
    "lastName": "Smith",
    "department": "Data Technician",
    "email": "fcox@example.org",
    "birthday": "1990-09-08"
}

###
DELETE http://localhost:5000/employees/679be01d535693251cfe96d0


